exp_name: lle 

train:
  warmup: True
  warmup_epoch: 10
  lr_warmup: 1e-6
  train_inp: ./lowlight/LOLdataset/our485/low 
  train_gt: ./lowlight/LOLdataset/our485/high 
  valid_inp: ./lowlight/LOLdataset/eval15/low 
  valid_gt: ./lowlight/LOLdataset/eval15/high
  batch_size: 4
  epoch: 2000
  lr: 1e-3
  num_workers: 0
  save_every: 20
  save_slim: true 

test:
  test_inp: ./lowlight/LOLdataset/eval15/low 
  test_gt: ./lowlight/LOLdataset/eval15/high
  num_workers: 0
  save: false

demo:
  demo_inp: ./lowlight/LOLdataset/eval15/low
  num_workers: 0

model:
  type: original # [original, re-parameterized]:
  pretrained: false
  need_slim: false # true
  rep_scale: 4
  channels: 12
