exp_name: isp 

train:
  warmup: false
  warmup_epoch: 10
  lr_warmup: 1e-6
  train_inp: ./isp/train/huawei_raw 
  train_gt: ./isp/train/canon 
  valid_inp: ./isp/test/huawei_raw 
  valid_gt: ./isp/test/canon 
  batch_size: 6
  epoch: 1000
  lr: 1e-3
  num_workers: 20
  save_every: 20
  save_slim: true 

test:
  test_inp: ./isp/test/huawei_raw 
  test_gt: ./isp/test/canon 
  num_workers: 0
  save: false

demo:
  demo_inp: ./traindata/isp/test/huawei_raw 
  num_workers: 0

model:
  type: original # [original, re-parameterized]
  pretrained: false
  need_slim: false #true 
  rep_scale: 4
  channels: 12
