exp_name: isp 

train:
  warmup: true
  warmup_epoch: 10
  lr_warmup: 1e-6
  train_inp: /media02/btlen05/ndbao/dataset/datasets/Zurich/train/huawei_raw 
  train_gt: /media02/btlen05/ndbao/dataset/datasets/Zurich/train/canon 
  valid_inp: /media02/btlen05/ndbao/dataset/datasets/Zurich/test/huawei_raw 
  valid_gt: /media02/btlen05/ndbao/dataset/datasets/Zurich/test/canon 
  batch_size: 6
  epoch: 2000
  lr: 1e-3
  num_workers: 4
  save_every: 20
  save_slim: true 

test:
  test_inp: /media02/btlen05/ndbao/dataset/datasets/Zurich/test/huawei_raw
  test_gt: /media02/btlen05/ndbao/dataset/datasets/Zurich/test/canon 
  num_workers: 0
  save: false

demo:
  demo_inp: ./traindata/isp/test/huawei_raw 
  num_workers: 0

model:
  type: original # [original, re-parameterized]
  pretrained: false
  need_slim: false #true 
  rep_scale: 4
  channels: 12
